### ISSUE TITLE
[bug] sfPegCardCmp - Peg card Display of formula field 

### ISSUE THREAD

**Issue by parii12** [pegros/PEG_LIST#40]
**Is your feature request related to a problem? Please describe.**
When editing on the peg card , the html tags always show up

**Describe the solution you'd like**
Display the formula field in html stripped format

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/27046738/198518453-f340d357-dc5c-4264-ae4f-3e3d7e7c1bf4.png)

![image](https://user-images.githubusercontent.com/27046738/198518943-38ace0a2-2df7-4c2b-92ae-0c963b7788ae.png)

**Comment by pegros** [comment]
@parii12 thanks for registering the issue.
I shall try to use **Lightning-output-field** instead when fields are disabled while keeping the current display.
This should solve this problem.
I shall also requalify this issue as a bug instead of a new feature request.

**Comment by pegros** [comment]
Fixed in commit [53a2bfd](https://github.com/pegros/PEG_LIST/commit/53a2bfddd6eded86a0b268a03b61672322e64709)
Actually replaced all disabled **input-fields** by **output-fields**, and it happens to match the standard behaviour of the standard record details component.
Also fixed some minor layout CSS elements to better segregate the different fields.
